### ISSUE TITLE
Exactly what I'm looking for but throws an error with Divi Builder plugin

### ISSUE THREAD

**Issue by maikunari** [limuelzoleta/custom-post-type-divi-module-ext#1]
Shows these two errors on front and back-end of WordPress when I install the plugin.  Does this work only with Divi theme or will it work with Divi Builder plugin as well?

`Warning: include(gc-custom-post-types.php): failed to open stream: No such file or directory in /nas/content/staging/friendlyfires/wp-content/plugins/custom-post-type-divi-module-ext-master/jlrz-custom-divi-modules.php on line 41`

`Warning: include(): Failed opening 'gc-custom-post-types.php' for inclusion (include_path='.:/usr/share/php') in /nas/content/staging/friendlyfires/wp-content/plugins/custom-post-type-divi-module-ext-master/jlrz-custom-divi-modules.php on line 41`

**Comment by maikunari** [comment]
Actually, I just renamed `include(gc-custom-post-types.php)` to `jlrz-divi-custom-post-types.php` and now it works.  

Next question, how to make it call the custom taxonomies attached to those custom post types?

**Comment by OvidiuZeicu** [comment]
Hey there...
I also managed to make it to install without errors, but how exactly does this work? I don't have a CPT dropdown or checkbox, or radio button, etc. to select from and using the input box it never show me any results, no matter what CPT slug in put in. Am I missing something? Thank you.

**Comment by limuelzoleta** [comment]
Hello, sorry for quite late response. I've already updated the files and fixed this error. This works, by entering the the post type you want to show. I'll add more features soon. Thanks for using this plugin!
