### ISSUE TITLE
Plugin only displays fullscreen for each item

### ISSUE THREAD

**Issue by sharpenedpixels** [limuelzoleta/custom-post-type-divi-module-ext#2]
Hi, I'm not sure if you were aware but your plugin only displays each item in fullscreen in the grid layout option. I want to be able to display 3 or 4 across the page like the existing blog module. Is this something you've missed or intend to add?

**Comment by jan1980** [comment]
Same problem here I guess we have to use CSS to correct it... otherwise please help!

**Comment by sambriggs172** [comment]
Yeah I had the same issues, otherwise it's really useful

**Comment by limuelzoleta** [comment]
The plugin has been updated to have the grid option. Thank you for your feedback.
